### ISSUE TITLE
Download Reports

### ISSUE THREAD

**Issue by 749** [TobiasFranek/webuntis#15]
Hello!
First of all, thanks for the great work on this library!
I was wondering if there is a way to download the Reports generated by WebUntis, specifically the Report which includes the Timetabledata.
Essentially I am trying to find out which teacher tought which classes in the current year.
Thank you for any help!

PS: Is there a documentation of the WebUntis JsonRPC API?

**Comment by TobiasFranek** [comment]
The docs of the api are an pdf i got sent from them, here you go.

[WebUntis JSON RPC API](https://github.com/TobiasFranek/webuntis/files/1418622/WebUntis_JSON_RPC_API.pdf)

Getting the classes a teacher taught is not possible at the moment due to missing api methods from webuntis.

**Comment by 749** [comment]
I have found a way, basically I am downloading the entire Timetable for one schoolyear and then filtering through the data. Only problem is it takes almost 10minutes for a single Teacher.
Anyways thanks for the information.
