### ISSUE TITLE
API Documentation!?!

### ISSUE THREAD

**Issue by jtuttas** [TobiasFranek/webuntis#16]
Hello there,
I've seen you PHP lib for webuntis. Well I would like to write some Wrapper Commands for Untis in Powershell (e.g. Get-Students, Get-Rooms etc.) and I am looking for a documentation (e.g. HTTP Request Types , CURL examples etc.) to do requests against WebUntis. Did you have any Informations about that!?!

Looking forward to hear from you.

best regards

jtuttas

**Comment by TobiasFranek** [comment]
I'm sorry but this doesnt belong to this repository, but you can write me an e-mail: tobias.franek@gmail.com.
