### ISSUE TITLE
Improve Docs Please

### ISSUE THREAD

**Issue by svin83** [TobiasFranek/webuntis#2]
I've been trying for ages to understand your readme's "Getting  Started" and "Basic Usage" sections, but It doesn't say anything about needing to install and use Composer.

I had to google everything on how to setup my LAMP-stack with memcached and get composer installed... I'm still stuck though...

I had to guess all this from googling the "composer require tfranek/webuntis" line...

There's nothing else to go by... Not even a hint....

The docs doesn't say anything on how to include/require this, where the config-array should be placed...

This NEEDS clarification, AND examples.

All my efforts just end up in an  HTTP ERROR 500

Please improve the docs, and please explain like I'm 5, so other noobs like me can use this too :)

**Comment by TobiasFranek** [comment]
I'm sorry, but the goal of the documentation is not to explain the php essentials like composer or installing extensions, there are plenty of good references out there. If you have set up composer correctly, and also have an composer.json the only thing you need to do is to write the console command mentioned in the installation. But if you have any questions or problems, you can DM me on [twitter](https://twitter.com/TobiasFranek) or write me an email: tobias.franek@gmail.com, because this doesn't belong into the github issues.

**Comment by svin83** [comment]
Sure. I know you'll have to draw the line somewhere regarding the noobproofing, but you could just add single lines for "make sure you have composer installed", "Make sure you have PHP installed and that memcached is installed and working correctly"  etc. this would make it easier for anyone to Google their way to a solution :)


Sendt fra min Samsung Galaxy-smarttelefon.
-------- Opprinnelig melding --------Fra: Tobias Franek <notifications@github.com> Dato: 09.06.2017  00:42  (GMT+01:00) Til: TobiasFranek/webuntis <webuntis@noreply.github.com> Ko: pigleet <svin83@gmail.com>, Author <author@noreply.github.com> Emne: Re: [TobiasFranek/webuntis] Improve Docs Please (#2) 
I'm sorry, but the goal of the documentation is not to explain the php essentials like composer or installing extensions, there are plenty of good references out there. If you have set up composer correctly, and also have an composer.json the only thing you need to do is to write the console command mentioned in the installation. But if you have any questions or problems, you can DM me on twitter or write me an email: tobias.franek@gmail.com, because this doesn't belong into the github issues.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TobiasFranek/webuntis","title":"TobiasFranek/webuntis","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/TobiasFranek/webuntis"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TobiasFranek in #2: I'm sorry, but the goal of the documentation is not to explain the php essentials like composer or installing extensions, there are plenty of good references out there. If you have set up composer correctly, and also have an composer.json the only thing you need to do is to write the console command mentioned in the installation. But if you have any questions or problems, you can DM me on [twitter](https://twitter.com/TobiasFranek) or write me an email: tobias.franek@gmail.com, because this doesn't belong into the github issues."}],"action":{"name":"View Issue","url":"https://github.com/TobiasFranek/webuntis/issues/2#issuecomment-307247266"}}}

**Comment by TobiasFranek** [comment]
I have added some lines to the README, the Requirements are clearer now (you dont really need memcached) and i added an link plus an sentence to the composer part in the installation. I hope i resolved this issue, if you have any further questions or feature requests for specifically this package, please submit another issue.
