### ISSUE TITLE
Doesn’t works without admin

### ISSUE THREAD

**Issue by JanMoritzMeyer** [TobiasFranek/webuntis#34]
I added path_scheme to my configuration but it still tries to get the data from the wrong server

**Comment by TobiasFranek** [comment]
can you please show more information (the code of the comfiguration)

**Comment by JanMoritzMeyer** [comment]
``<?php
require_once 'vendor/autoload.php';
use Webuntis\Configuration\WebuntisConfiguration;
use Webuntis\Query\Query;
$config = new WebuntisConfiguration([
'default' => [
  'server' => 'stundenplan.hamburg.de',
  'school' => 'Hh5868',
  'username' => 'xxx',
  'password' => 'xxx',
  'path_scheme' => 'https://stundenplan.hamburg.de/WebUntis/jsonrpc.do?school={school}'
 ],
'admin' => [
 'server' => 'stundenplan.hamburg.de',
 'school' => 'Hh5868',
 'username' => 'xxx',
 'password' => 'xxx',
 'path_scheme' => 'https://stundenplan.hamburg.de/WebUntis/jsonrpc.do?school={school}'
 ]
 ]);
 $query = new Query();
 $query = $query->get('Period');
 log($query);
 ?>
``

**Comment by TobiasFranek** [comment]
do you know for certain that the false path_scheme is set? And which version are you using this feature is only supported in 3.0.

**Comment by JanMoritzMeyer** [comment]
I installed the version today with composer but in the composer.json its only 2.2, how can I install 3.0?

**Comment by TobiasFranek** [comment]
just change the version in the composer.json file and run composer update.

**Comment by JanMoritzMeyer** [comment]
Okay, that works now. Is there any possibility now to just use an default user? We dont have any access to an admin user...

**Comment by TobiasFranek** [comment]
yea sure if you only set the default user it will work nevertheless, but some API routes cannot be executed, because they need special reading rights

**Comment by TobiasFranek** [comment]
ok this is a bug, i will fix this as soon as possible, but just set it with sample data and i should still work.

**Comment by TobiasFranek** [comment]
Ok I looked into the bug and it is expected behavior, because for example in the Period Model you have alot of children and these children are, for example Teacher or Students, which are protected by the admin wall. This means: You can fetch Period without, but when the childs are fetched like Teacher and Students they require an admin account which can read Teachers and Students.

**Comment by TobiasFranek** [comment]
So this would be a feature to enable it so that children will not be rendered and the original content will be but in as array

**Comment by TobiasFranek** [comment]
will be solved in #39

**Comment by JanMoritzMeyer** [comment]
okay nice, cause I cant find any documentation for the API do you have one? If so, can you send it to me so I can work with that?

**Comment by TobiasFranek** [comment]
you can read more about how you can avoid the admin is not set error in the [Configuration docs](https://github.com/TobiasFranek/webuntis/blob/master/docs/BasicUsage/Configuration.md) and there where the 'ignore_children' property is mentioned.

**Comment by TobiasFranek** [comment]
[WebUntis_JSON_RPC_API.pdf](https://github.com/TobiasFranek/webuntis/files/2340729/WebUntis_JSON_RPC_API.pdf)
