### ISSUE TITLE
WebUnits repository model is proteced

### ISSUE THREAD

**Issue by Mastermori** [TobiasFranek/webuntis#35]
When I try to log into my school with the admin and default user set to the same user (although it's not an admin, just setting the default doesn't work but thats an issue for another day) and then query the Period repository it gives me this:
`Webuntis\Repositories\Repository Object ( [model:protected] => Webuntis\Models\Students [instance:protected] => Webuntis\Webuntis Object ( [path:Webuntis\Webuntis:private] => https://stundenplan.hamburg.de/WebUntis/jsonrpc.do?school=Hh5868 [client:Webuntis\Webuntis:private] => Webuntis\Client\Client Object ( [requiredHttpHeaders:Datto\JsonRpc\Http\Client:private] => Array ( [Accept] => application/json [Content-Type] => application/json [Connection] => close ) [uri:Datto\JsonRpc\Http\Client:private] => https://stundenplan.hamburg.de/WebUntis/jsonrpc.do?school=Hh5868 [headers:Datto\JsonRpc\Http\Client:private] => Array ( [Accept] => application/json [Content-Type] => application/json [Connection] => close [Cookie] => JSESSIONID=39E33EE814222D158102EB94FF825492.nodeTC01; Path=/WebUntis; Version=1; Max-Age=1209600; Expires=Wed, 12-Sep-2018 08:37:05 GMT; ) [context:Datto\JsonRpc\Http\Client:private] => Resource id #20 [client:Datto\JsonRpc\Http\Client:private] => Datto\JsonRpc\Client Object ( [messages:Datto\JsonRpc\Client:private] => Array ( ) ) ) [currentUserId:Webuntis\Webuntis:private] => 224 [currentUserType:Webuntis\Webuntis:private] => 1 [context:Webuntis\Webuntis:private] => admin ) [cache:protected] => [executionHandler:protected] => Webuntis\Handler\ExecutionHandler Object ( [cache:Webuntis\Handler\ExecutionHandler:private] => ) ) `
So this suggest that I don't have access to the Periods which I know to be false because I can log in to the Web Untis mobile app with that exact data.
Do I need to get an admin-read-only account from my school to get access to the Periods?

**Comment by TobiasFranek** [comment]
if you want the data from the request execute ->findAll() or other method. Please read the [docs](https://github.com/TobiasFranek/webuntis/blob/master/docs/BasicUsage/Querys.md) under Querys and then how to handle Repositories.

**Comment by Mastermori** [comment]
Thank you for the quick response but
`Uncaught Webuntis\Exceptions\ModelException: There is no Model available for the user type: "1"`
is what I get when I try to run the ->findAll() on the $query->get('Period') like this:
`print_r($query->get('Period')->findAll());`

**Comment by Mastermori** [comment]
My config looks like this:
`$config = new WebuntisConfiguration([
'admin' => [
  'server' => 'stundenplan.hamburg.de',
  'school' => 'hh5868',
  'username' => '???',
  'password' => '???',
  'path_scheme' => 'https://{server}/WebUntis/jsonrpc.do?school={school}'
],
'default' => [
  'server' => 'stundenplan.hamburg.de',
  'school' => 'hh5868',
  'username' => '???',
  'password' => '???',
  'path_scheme' => 'https://{server}/WebUntis/jsonrpc.do?school={school}'
 ]
 ]);`
what might or might not be of interest is that the username starts with the number 1.

**Comment by TobiasFranek** [comment]
are your logged in with an klasse object?

**Comment by Mastermori** [comment]
No, I'm not, just the default config, I found another libary that works easier now, sorry for bothering you but keep up the good work ^^

**Comment by TobiasFranek** [comment]
yea this library is more for advanced usage, but I'm glad you found your fit.

**Comment by TobiasFranek** [comment]
will be solved in #37 #38 #39
