### ISSUE TITLE
no Model available for the user type: "0" 

### ISSUE THREAD

**Issue by loetmann** [TobiasFranek/webuntis#36]
Hello,
just installed your library and everything looks good so far, but every time I issue queriessr relating to users I'll get:

Fatal error: Uncaught Webuntis\Exceptions\ModelException: There is no Model available for the user type: "0" in /Users/ralfk/PhpstormProjects/webuntis/vendor/tfranek/webuntis/src/Webuntis.php:98
Stack trace:
#0 /Users/ralfk/PhpstormProjects/webuntis/vendor/tfranek/webuntis/src/Repositories/PeriodRepository.php(38): Webuntis\Webuntis->getCurrentUser()
#1 /Users/ralfk/PhpstormProjects/webuntis/test1.php(67): Webuntis\Repositories\PeriodRepository->findBy(Array)
#2 {main}
  thrown in /Users/ralfk/PhpstormProjects/webuntis/vendor/tfranek/webuntis/src/Webuntis.php on line 98

Example: 

$test = $query->get('Period')->findBy(['teachers:name' => 'We']);

Obviously there is a Problem with getCurrentUser() and getCurrentUserType(). I use a config with dsiable_cache and only_admin set to true.

The Admin User is a simple User with appropriate rights and roles in Webuntis. As a saw in another thread you distinguish UserTypes only for 2 and 5.

Allthough the documentation is very minimalistic I love your approach. Only thing missing: some more examples in the documentation and the booking stuff for resources, rooms etc.

Regards

**Comment by loetmann** [comment]
Tweaking around with the Admin-Account in WebUntis: I now have the userType 16 ....

**Comment by TobiasFranek** [comment]
yea im aware of this "bug", somehow some strange usertypes are being returned i have to look into that, the api documentation states that there are 2 logged in user types (2 for Teachers and 5 for Students)

**Comment by TobiasFranek** [comment]
and yes i know that there is missing documentation but at the moment i dont have so much time that i can concentrate on the documentation, i mostly focus on additional features/bugfixes with the spare time i have

**Comment by TobiasFranek** [comment]
if you have a better documentation about the user types or general the authentication please share them

**Comment by TobiasFranek** [comment]
later that day i will try to put out a new release that adresses these issues so if you have any suggestion please let me know

**Comment by loetmann** [comment]
You are aware of the major upgrades to webuntis 2019 of Webuntis servers this week?
Obviously they have a compete new Role and ACL model, ok perhaps a new GUI.

**Comment by TobiasFranek** [comment]
hmmm no not really im not that involved in that anymore. Do you have some kind of docs or do you know where to find them?

**Comment by loetmann** [comment]
Technical doumentation: No, I never found them. I ever wondered about your sources ....

But they updated their Customer/User documentation:

https://www.untis.at/HTML/webuntis_manuals.php

and there is also a release Note:

https://www.untis.at/Downloads/int/Manuals/de/WebUntis2019.pdf

Chapter 3 is about the new Role/ACL-Model. 

Regards

**Comment by TobiasFranek** [comment]
ok today i will into that, i already have an idea how to fix that! expect
an Release tonight or tomorow.

Am Fr., 31. Aug. 2018 um 11:13 Uhr schrieb loetmann <
notifications@github.com>:

**Comment by loetmann** [comment]
Great

**Comment by TobiasFranek** [comment]
will be solved in #37 and #38

**Comment by TobiasFranek** [comment]
this issue should be fixed now you can read more about the newly added property in the (Configuration)[https://github.com/TobiasFranek/webuntis/blob/master/docs/BasicUsage/Configuration.md] and there where the user_type section is mentioned. But if you only use the Period you will not have to worry about anything.
