### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by leschi** [TobiasFranek/webuntis#46]
Hi,

do you have a working example for your project ?

I have some problems to use this api ;D

maybe your sample would help me.

thanks a lot !!

**Comment by TobiasFranek** [comment]
Yea, i really need to add some examples. What are you trying todo?

**Comment by leschi** [comment]
I only want to get the user information.
like email name etc..

**Comment by TobiasFranek** [comment]
Ok i will write up one when i am at home currently on Work. Expect it tonight

**Comment by leschi** [comment]
WOW! thanks a lot !

**Comment by leschi** [comment]
thanks a lot! this helped me !
