### ISSUE TITLE
No right to getTeachers()

### ISSUE THREAD

**Issue by Mastermori** [TobiasFranek/webuntis#48]
So, me and my friend are using different apis now but with all of them we get the same problem: We have no right to get the teachers..
We know that it should be possible to get them because other apps like the official Untis Mobile App have access to the teachers but we just cant figure out, how to even get there shorts or anything else than their id.
We always get "no right for getTeachers() " which makes no sense to me..
Do you know why this is or how to work around it?
I am sorry if this isn't really about your api but we really need help ^^

**Comment by TobiasFranek** [comment]
Yes, you have to configure the user in the settings of the backend so the user has read access to the Teacher resource. As this is not related to this repository im closing this issue.

**Comment by Mastermori** [comment]
Yea, I know that, but how comes the WebUntis App **has** access to the teachers and I don't if we use the same login data?
Thank you for your answer, even though this is unrelated ^^

**Comment by TobiasFranek** [comment]
I obviously dont really know how they do things, but i think the application (Web, Phone) are seperate to the JSON RPC doc and they also need somekind of other authentication

**Comment by Mastermori** [comment]
Ok, thanks a lot for taking the time to answer this ^^
