### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Webuntis\Configuration\WebuntisConfiguration' not found

### ISSUE THREAD

**Issue by hstop** [TobiasFranek/webuntis#49]
Hi,

I'm trying to get your project running on XAMPP. I installed it via composer and tried to use your [sample](https://github.com/TobiasFranek/webuntis/issues/46).

I'm getting the following error.

> Fatal error: Uncaught Error: Class 'Webuntis\Configuration\WebuntisConfiguration' not found in C:\xampp\htdocs\webuntis\test.php:5 Stack trace: #0 {main} thrown in C:\xampp\htdocs\webuntis\test.php on line 5

Do I need to add anything else?

Thx in advance.

**Comment by TobiasFranek** [comment]
Can you please show me the code, or else i cant really see what you could have done wrong.

**Comment by hstop** [comment]
It's the code from your sample:

`<?php
 require_once __DIR__ . '/vendor/autoload.php';

$config = new \Webuntis\Configuration\WebuntisConfiguration([
    'default' => [
        //f.e. thalia, cissa etc.
        'server' => 'yourserver',
        'school' => 'yourschool',
        'username' => 'yourname',
        'password' => 'yourpassword'
    ], 
    'admin' => [
        'server' => 'yourserver',
        'school' => 'yourschool',
        'username' => 'youradmin',
        'password' => 'youradminpassword'
    ]
]);

$query = new \Webuntis\Query\Query();

$format = 'json';
//format can also be null

// Students
$serializedContend = Webuntis\Serializer\Serializer::serialize($query->get('Students')->findAll(), $format);

// Teachers
$serializedContend = Webuntis\Serializer\Serializer::serialize($query->get('Teachers')->findAll(), $format);
?>`

**Comment by TobiasFranek** [comment]
I think your path to the autoload.php is wrong. It should be __DIR__ and not DIR. If this does not work print the path of the autoload.php and check if it is the correct one, if not change the path so it is the same.

**Comment by TobiasFranek** [comment]
I'm sorry i didn't know that `__DIR__` will be __DIR__

**Comment by TobiasFranek** [comment]
but still check if the autoload is required

**Comment by hstop** [comment]
autoload is required correctly. When I rename it, the correct error is fired.

**Comment by TobiasFranek** [comment]
Which PHP Version do you have?

**Comment by hstop** [comment]
XAMPP with PHP 7.2.12

**Comment by TobiasFranek** [comment]
And the lib is in the right directory with the right namespace?

**Comment by hstop** [comment]
what I did:
 - unpacked the files in /src from your package to /htdocs/webuntis
- installed composer and ran > composer require tfranek/webuntis
- copied composer.json to /htdocs/webuntis and ran composer install

so folder structure is
/htdocs
  >/webuntis
     >/CacheBuilder
     >/Client
     >/Command
     >/Configuration
     >/Exceptions
     >/Handler
     >/Models
     >/Query
     >/Repositories
     >/Resources
     >/Security
     >/Serializer
     >/Types
     >/Vendor

**Comment by TobiasFranek** [comment]
OK so thats not quite how you Install a composer package. Install composer. Add a composer.json with composer init. And after that just run composer require ...

**Comment by TobiasFranek** [comment]
For more information please see the composer docs

**Comment by TobiasFranek** [comment]
Do you have valid Login Info? For students your account also needs special rights, atleast in my school this was the case.

**Comment by hstop** [comment]
I'm a teacher an have a valid log in and probably the neccessary rights.
How do I enter spaces in the school name?

**Comment by TobiasFranek** [comment]
There should not be spaces in the school name, the schoolname for the lib school be found in the url or not so you just leave it blank.

**Comment by hstop** [comment]
Our school name has spaces in it. When loggin into Webuntis in the url the spaces are replaces by +
That's how I entered them into the config.

**Comment by TobiasFranek** [comment]
Try "Classes" instead of students this model should not ned Special Access rights

**Comment by hstop** [comment]
worked! Thanx!

Now I need to find out why I don't have elevated rights and how to set them.

**Comment by TobiasFranek** [comment]
Yes exactly in webuntis there is a tab were you can configure the Access right for certain groups when you are Admin. But there i cant help you :). Im closing this issued now, please leave a star if like the library.
