### ISSUE TITLE
absences

### ISSUE THREAD

**Issue by hstop** [TobiasFranek/webuntis#51]
Hi,

sorry for posting on this matter again. I was in contact with Untis about the API and they sent me the documentation.

It turns out, that there is the method getTimetableWithAbsences() which is exactly what I need.
Unfortunately this method seems not to be implemented in your library. Is there a chance that you make that passible?

Greetings Mathias

**Comment by TobiasFranek** [comment]
This method isn't in my docs, i think it's pretty new. Can you send me this documentation?

**Comment by hstop** [comment]
Is there a way to contact you in private since I don't want to share the documentation publicly. i'm sure whether Untis would approve that.

**Comment by TobiasFranek** [comment]
tobias.franek@gmail.com is my Email adress
